name: render readme

on:
  # Trigger the workflow on a successful merge
  # but only for the main branch
  push:
    branches:
      - main
    paths-ignore: # Don't trigger on files that are updated by the CI
      - '.gitignore'
      - 'README.md'
      - '.github/**'

jobs:
  run-rmarkdown:
    name: Render index
    runs-on: windows-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("backports", "rmarkdown", "DT", "purrr"))'

    # Render READEME.md using rmarkdown
    - name: render index.html
      run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'

    - name: commit rendered README
      run: |
        git add index.html 
        git commit -m "Re-build index.html" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
