on:
  # Trigger the workflow on a successful merge
  # but only for the main branch
  push:
    branches:
      - main
    paths-ignore: # Don't trigger on files that are updated by the CI
      - '.gitignore'
      - 'README.md'
      - '.github/**'

name: Render index.rmd

jobs:
  run-rmarkdown:
    name: Render index
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Run run_scrpit.R
        run: Rscript -e 'source("./scripts/run_rscript.R")'
      - name: Commit results
        run: |
          git commit index.html -m 'commit updated index.html' 
          git push origin 

